### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by saichandrapandraju** [ncoop57/function_parser#6] opened 2021-09-30 05:14 UTC
Hi @ncoop57 , 

Thanks for the great work!!!
Can I use this in windows? Because when I setup this in my windows machine, `DataProcessor.PARSER.set_language` is not working. Just out of curiosity, I opened `tree-sitter-languages.so` file and I found this - 

![image](https://user-images.githubusercontent.com/41769919/135391263-e93f7c8f-742c-4123-9fa8-c127e0387870.png)

Could you suggest how to solve this..?

**Comment by 0xCMars** [comment] 2021-11-09 08:00
This problem is caused by the tree-sitter, it seems that the old version of the tree-sitter had some issues on Windows x64, but they had fixed the bug with a new version, so you need to install a slightly newer version

**Comment by ncoop57** [comment] 2021-11-11 18:50
@MarsChenSE Do you know which version specifically works with Windows? I worry having a new version of tree-sitter because the current implementation of function_parser needs a very specific one to avoid breaking compatibility. It has been on my todo list for a long time to overhaul function_parser to the newest version of tree-sitter as the newest tree-sitter has a way easier to use API, but limited time prevents it. So, if the newer version of tree-sitter that works with Windows x64, but not function-parser, it would probably be better to use WSL on Windows (not 100% sure if this will by pass the problem, but it might)

**Comment by ncoop57** [comment] 2022-05-04 17:10
Closing this for now

**Closed as completed by ncoop57** 2022-05-04 17:10 UTC
